version: '3.1'
services:
    db:
        image: mariadb:latest
        container_name: lexbib_db
        restart: always
        volumes:
            - ./data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=lexbib_root
            - MYSQL_PASSWORD=An0thrS3crt
            - MYSQL_USER=lexbib_user
            - MYSQL_DATABASE=lexbib_db
        ports:
            - 3315:3306
