version: '3.1'
services:
    db:
        image: mariadb:latest
        container_name: alexander_db
        restart: always
        volumes:
            - ./data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=alexander_root
            - MYSQL_PASSWORD=An0thrS3crt
            - MYSQL_USER=alexander_user
            - MYSQL_DATABASE=alexander_db
        ports:
            - 3315:3306
